name: Validation

on:
  pull_request:
  push:
    branches: [ main ]
    tags: [ '*' ]
  workflow_dispatch:

# concurrency:
#   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
#   cancel-in-progress: true

jobs:
  validation:
    uses: JeffersonLab/clas12-validation/.github/workflows/ci.yml@b218a730d693e83359dfeb1e1fe6ef2536433d0c
