name: Validation

on:
  pull_request:
  push:
    branches: [ main ]
    tags: [ '*' ]
  workflow_dispatch:

concurrency:
  group: ${{ github.run_id }}
  cancel-in-progress: false

jobs:
  validation:
    uses: JeffersonLab/clas12-validation/.github/workflows/ci.yml@bump-actions
