name: Validation

on:
  pull_request:
  push:
    branches: [ main ]
    tags: [ '*' ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  validation:
    uses: JeffersonLab/clas12-validation/.github/workflows/ci.yml@update-concurrency
